name: my_package
description: pub.dev lecture demo package
version: 0.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  eo_color: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
